config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :comments

      resources :favorited_brands

      resources :brands

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :comments
  resources :favorited_brands
  resources :brands
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorited_brand.rb
class FavoritedBrand < ApplicationRecord
  # Direct associations

  belongs_to :user,
             foreign_key: "brand_id"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/favorited_brands_controller.rb
class Api::V1::FavoritedBrandsController < Api::V1::GraphitiController
  def index
    favorited_brands = FavoritedBrandResource.all(params)
    respond_with(favorited_brands)
  end

  def show
    favorited_brand = FavoritedBrandResource.find(params)
    respond_with(favorited_brand)
  end

  def create
    favorited_brand = FavoritedBrandResource.build(params)

    if favorited_brand.save
      render jsonapi: favorited_brand, status: :created
    else
      render jsonapi_errors: favorited_brand
    end
  end

  def update
    favorited_brand = FavoritedBrandResource.find(params)

    if favorited_brand.update_attributes
      render jsonapi: favorited_brand
    else
      render jsonapi_errors: favorited_brand
    end
  end

  def destroy
    favorited_brand = FavoritedBrandResource.find(params)

    if favorited_brand.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: favorited_brand
    end
  end
end

app/controllers/favorited_brands_controller.rb
class FavoritedBrandsController < ApplicationController
  before_action :set_favorited_brand, only: %i[show edit update destroy]

  def index
    @q = FavoritedBrand.ransack(params[:q])
    @favorited_brands = @q.result(distinct: true).includes(:user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @favorited_brand = FavoritedBrand.new
  end

  def edit; end

  def create
    @favorited_brand = FavoritedBrand.new(favorited_brand_params)

    if @favorited_brand.save
      message = "FavoritedBrand was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @favorited_brand, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @favorited_brand.update(favorited_brand_params)
      redirect_to @favorited_brand,
                  notice: "Favorited brand was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @favorited_brand.destroy
    message = "FavoritedBrand was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to favorited_brands_url, notice: message
    end
  end

  private

  def set_favorited_brand
    @favorited_brand = FavoritedBrand.find(params[:id])
  end

  def favorited_brand_params
    params.require(:favorited_brand).permit(:brand_id)
  end
end

app/views/favorited_brands/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Favorited Brand #<%= favorited_brand.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Brand</dt>
      <dd>
        <% if @favorited_brand.user.present? %>
          <%= link_to favorited_brand.user, favorited_brand.user %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back favorited_brand, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_favorited_brand_url(favorited_brand), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to favorited_brand, method: :delete, data: { confirm: "Do you really want to delete this favorited_brand?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(favorited_brand.updated_at) %> ago
  </div>
</div>

app/views/favorited_brands/_favorited_brands_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "favorited_brands_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_username_cont, "User username contains" %>
    <%= f.text_field :user_username_cont, :class => "form-control", :placeholder => "User username contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/favorited_brands" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#favorited_brands_filters">
  Show filters
</a>

app/views/favorited_brands/_form.html.erb
<% was_validated = favorited_brand.errors.any? %>

<%= form_with(model: favorited_brand, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% brand_class = "form-control" %>
    <% brand_was_invalid = favorited_brand.errors.include?(:brand) %>

    <% if was_validated %>
      <% if brand_was_invalid %>
        <% brand_class << " is-invalid" %>
      <% else %>
        <% brand_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :brand_id %>
    <%= f.collection_select :brand_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if brand_was_invalid %>
      <% favorited_brand.errors.full_messages_for(:brand).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/favorited_brands/_list_item.html.erb
<%= link_to favorited_brand, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= favorited_brand %>
    <small class="text-muted">
      <%= time_ago_in_words(favorited_brand.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/favorited_brands/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Favorited Brand #<%= @favorited_brand.id %>
      </h2>

      <div class="card-body">
        <%= render "form", favorited_brand: @favorited_brand %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorited_brands/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Favorited Brands

      <%= link_to new_favorited_brand_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "favorited_brands/favorited_brands_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Favorited Brands

        <%= link_to new_favorited_brand_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @favorited_brands, partial: "list_item", as: :favorited_brand %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @favorited_brands, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/favorited_brands/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Favorited Brand
      </h2>

      <div class="card-body">
        <%= render "form", favorited_brand: @favorited_brand %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorited_brands/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @favorited_brand, partial: "card", as: :favorited_brand %>
  </div>
</div>