config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :comments

      resources :favorited_brands

      resources :brands

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :comments
  resources :favorited_brands
  resources :brands
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  mount_uploader :image, ImageUploader

  # Direct associations

  has_many   :comments,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/brands_controller.rb
class Api::V1::BrandsController < Api::V1::GraphitiController
  def index
    brands = BrandResource.all(params)
    respond_with(brands)
  end

  def show
    brand = BrandResource.find(params)
    respond_with(brand)
  end

  def create
    brand = BrandResource.build(params)

    if brand.save
      render jsonapi: brand, status: :created
    else
      render jsonapi_errors: brand
    end
  end

  def update
    brand = BrandResource.find(params)

    if brand.update_attributes
      render jsonapi: brand
    else
      render jsonapi_errors: brand
    end
  end

  def destroy
    brand = BrandResource.find(params)

    if brand.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: brand
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[show edit update destroy]

  def index
    @q = Brand.ransack(params[:q])
    @brands = @q.result(distinct: true).includes(:comments).page(params[:page]).per(10)
  end

  def show
    @comment = Comment.new
  end

  def new
    @brand = Brand.new
  end

  def edit; end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand, notice: "Brand was successfully created."
    else
      render :new
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: "Brand was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @brand.destroy
    redirect_to brands_url, notice: "Brand was successfully destroyed."
  end

  private

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :description, :image, :sport,
                                  :category, :pricepoint, :highlyrated)
  end
end

app/views/brands/_brand_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Comments

    <a data-toggle="collapse" href="#brand_comments_new_form">
      Add comment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @brand.comments.each do |comment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to comment, comment %>

        <%= link_to comment, method: :delete, data: { confirm: "Do you really want to delete this comment" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="brand_comments_new_form">
        <%= render partial: "brands/brand_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/brands/_brand_comments_new_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>

  <%= f.hidden_field :brand_id, value: @brand.id %>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/brands/_brands_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "brands_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :highlyrated_cont, "Highlyrated contains" %>
    <%= f.text_field :highlyrated_cont, :class => "form-control", :placeholder => "Highlyrated contains" %>
  </div>

  <div class="form-group">
    <%= f.label :pricepoint_cont, "Pricepoint contains" %>
    <%= f.text_field :pricepoint_cont, :class => "form-control", :placeholder => "Pricepoint contains" %>
  </div>

  <div class="form-group">
    <%= f.label :category_cont, "Category contains" %>
    <%= f.text_field :category_cont, :class => "form-control", :placeholder => "Category contains" %>
  </div>

  <div class="form-group">
    <%= f.label :sport_cont, "Sport contains" %>
    <%= f.text_field :sport_cont, :class => "form-control", :placeholder => "Sport contains" %>
  </div>

  <div class="form-group">
    <%= f.label :description_cont, "Description contains" %>
    <%= f.text_field :description_cont, :class => "form-control", :placeholder => "Description contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/brands" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#brands_filters">
  Show filters
</a>

app/views/brands/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Brand #<%= brand.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= brand.name %></dd>

      <dt>Description</dt>
      <dd><%= brand.description %></dd>

      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @brand.image, class: "img-fluid" %>
      </dd>

      <dt>Sport</dt>
      <dd><%= brand.sport %></dd>

      <dt>Category</dt>
      <dd><%= brand.category %></dd>

      <dt>Pricepoint</dt>
      <dd><%= brand.pricepoint %></dd>

      <dt>Highlyrated</dt>
      <dd><%= brand.highlyrated %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back brand, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_brand_url(brand), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to brand, method: :delete, data: { confirm: "Do you really want to delete this brand?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(brand.updated_at) %> ago
  </div>
</div>

app/views/brands/_form.html.erb
<% was_validated = brand.errors.any? %>

<%= form_with(model: brand, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = brand.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% brand.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% description_class = "form-control" %>
    <% description_was_invalid = brand.errors.include?(:description) %>

    <% if was_validated %>
      <% if description_was_invalid %>
        <% description_class << " is-invalid" %>
      <% else %>
        <% description_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :description %>
    <%= f.text_field :description, class: description_class, placeholder: "Enter description" %>
    <% if description_was_invalid %>
      <% brand.errors.full_messages_for(:description).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = brand.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% brand.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% sport_class = "form-control" %>
    <% sport_was_invalid = brand.errors.include?(:sport) %>

    <% if was_validated %>
      <% if sport_was_invalid %>
        <% sport_class << " is-invalid" %>
      <% else %>
        <% sport_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :sport %>
    <%= f.text_field :sport, class: sport_class, placeholder: "Enter sport" %>
    <% if sport_was_invalid %>
      <% brand.errors.full_messages_for(:sport).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% category_class = "form-control" %>
    <% category_was_invalid = brand.errors.include?(:category) %>

    <% if was_validated %>
      <% if category_was_invalid %>
        <% category_class << " is-invalid" %>
      <% else %>
        <% category_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :category %>
    <%= f.text_field :category, class: category_class, placeholder: "Enter category" %>
    <% if category_was_invalid %>
      <% brand.errors.full_messages_for(:category).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% pricepoint_class = "form-control" %>
    <% pricepoint_was_invalid = brand.errors.include?(:pricepoint) %>

    <% if was_validated %>
      <% if pricepoint_was_invalid %>
        <% pricepoint_class << " is-invalid" %>
      <% else %>
        <% pricepoint_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :pricepoint %>
    <%= f.text_field :pricepoint, class: pricepoint_class, placeholder: "Enter pricepoint" %>
    <% if pricepoint_was_invalid %>
      <% brand.errors.full_messages_for(:pricepoint).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% highlyrated_class = "form-control" %>
    <% highlyrated_was_invalid = brand.errors.include?(:highlyrated) %>

    <% if was_validated %>
      <% if highlyrated_was_invalid %>
        <% highlyrated_class << " is-invalid" %>
      <% else %>
        <% highlyrated_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :highlyrated %>
    <%= f.text_field :highlyrated, class: highlyrated_class, placeholder: "Enter highlyrated" %>
    <% if highlyrated_was_invalid %>
      <% brand.errors.full_messages_for(:highlyrated).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/brands/_list_item.html.erb
<%= link_to brand, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= brand %>
    <small class="text-muted">
      <%= time_ago_in_words(brand.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/brands/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Brand #<%= @brand.id %>
      </h2>

      <div class="card-body">
        <%= render "form", brand: @brand %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/brands/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Brands

      <%= link_to new_brand_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "brands/brands_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Brands

        <%= link_to new_brand_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @brands, partial: "list_item", as: :brand %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @brands, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/brands/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Brand
      </h2>

      <div class="card-body">
        <%= render "form", brand: @brand %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/brands/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @brand, partial: "card", as: :brand %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "brands/brand_comments" %>
  </div>
</div>